"""empty message

Revision ID: 49dd988ad6df
Revises: 3b43215dd705
Create Date: 2023-10-16 15:36:36.720722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49dd988ad6df'
down_revision = '3b43215dd705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('prep_time')
        batch_op.drop_column('bake_time')
        batch_op.drop_column('rise_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rise_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bake_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
